# Generated by Django 2.2.6 on 2019-11-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=40, verbose_name='Título de la noticia')),
                ('imagen', models.ImageField(upload_to='img', verbose_name='Fotografía de la notica')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('resumen_noticia', models.TextField(default='...', verbose_name='Breve resumen de la notica')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('escrita_por', models.CharField(default='CANICA', max_length=60)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
